### PR TITLE
Add Material flat button support

### PR DESCRIPTION
**Pull request by rynop**
Per https://github.com/michaeldoye/mat-progress-buttons/issues/16

Of note, I had to update your package.json because it used a version of event-stream (3.3.6) which had a HUGE vuln and was [removed by NPM](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).

The large # of diffs on package.json are due to the fact that npm now alphabetizes dependencies.

### CODE REVIEW

**Comment by michaeldoye** [comment]
Thanks for the PR, have been super busy on my side so this is really helpful :) Will review and merge after work this evening.

**Comment by rynop** [comment]
Np. I'll add Fab button in here too this am. Will only take a minute and will allow u to kill 2 birds when you review.

**Comment by rynop** [comment]
Added fab button support. 

I omitted `fab` from Bar Button README cuz it looks janky:
image

If you don't want support for fab in bar, just LMK and I'll remove from bar-button.component.html

**Comment by michaeldoye** [comment]
This is awesome, thanks dude! 

Yeah, I think lets leave the fab out of the bar button and add a note in the readme to say that fab can only be used with spinner button... For now. 

In a future release I want to add something like this demo (angular material 1): https://codepen.io/DevVersion/pen/vGebGB for the bar button

**Comment by rynop** [comment]
Ohh thats freaking slick!  Man, now I want that!

I've removed fab from bar, added note to README.

I really like that spinner around the fab, I may make time to add that soon :)

**Comment by michaeldoye** [comment]
Great, thanks!

Hahaha yeah it is quite nice indeed :)

Thanks again for the contributions, will merge your pr in a few hours.

**Pull request merged**
